### PR TITLE
fix: store directly at the closest peers

### LINKED ISSUE #41: Store directly at nodes
Update the APIs to move away from kad provider, and simply get closest nodes

### PR DESCRIPTION
**Pull request by RolandSherwin**
closes #41

### CODE REVIEW

File: safenode/src/network/msg/mod.rs [hunk 1]
```diff
@@ -7,8 +7,8 @@
 // permissions and limitations relating to use of the SAFE Network Software.
 
 mod codec;
+pub use codec::{Cmd, CmdResponse, Query, QueryResponse, Request, Response};
```
Comment (maqi) [inline safenode/src/network/msg/mod.rs:10]: the naming of `Cmd`, `Query` and `Request/Response` is bit overlapping.
If do want to divide the communications based on the usage, better give a more explicit naming.
and same if divide based on the targets (i.e. client-node, or among nodes)

File: safenode/src/node/api.rs [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+
+use super::error::Result;
+use crate::{
+    network::{Cmd, Query, Request},
+    storage::chunks::Chunk,
+};
+
+use super::Node;
+
+impl Node {
```
Comment (maqi) [inline safenode/src/node/api.rs:22]: better have a name like `Vault` (or even just DataHolder) if it only handles the data storage duty?
`Node` means it also needs to handle the `network knowledge` and other duties ?

File: safenode/src/node/api.rs [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+            let req = Request::Cmd(Cmd::StoreChunk(data.clone()));
+            let future = Box::pin(tokio::time::timeout(
+                Duration::from_secs(5),
+                self.network.send_request(req, node),
+            ));
+            sent_futures.push(future);
+        }
+
+        let mut responses = Vec::new();
+        while !sent_futures.is_empty() {
```
Comment (maqi) [inline safenode/src/node/api.rs:38]: we may don't care of the response of `store data` ?
anyway, no harm to keep it unless it blocks the flow or affect the performance

File: safenode/src/node/api.rs [hunk 4]
```diff
@@ -0,0 +1,87 @@
...
+            match select_all(sent_futures).await {
```
Comment (maqi) [inline safenode/src/node/api.rs:71]: only expect one response shall be enough?

also, this seems a blocking call ?

File: safenode/src/node/api.rs [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+                (Ok(res), _, remaining_futures) => {
+                    info!("got response for get_data: {res:?}");
```
Comment (maqi) [inline safenode/src/node/api.rs:73]: loging the whole chunk could be lengthy.
unless the `Debug` formt of `res` only logs the name of the content?

File: safenode/src/node/mod.rs [hunk 6]
```diff
@@ -0,0 +1,132 @@
...
+            node_events_channel: node_events_channel.clone(),
+        };
+        let mut node_clone = node.clone();
+
+        // Spawn the network task for it to run in the background.
+        let _ = spawn(network_event_loop.run());
+
+        let _ = spawn(async move {
+            loop {
+                let event = match network_events.next().await {
```
Comment (maqi) [inline safenode/src/node/mod.rs:60]: shall be the `try_next` call here?

File: safenode/src/node/mod.rs [hunk 7]
```diff
@@ -0,0 +1,132 @@
...
+        &mut self,
+        request: Request,
+        response_channel: ResponseChannel<Response>,
+    ) -> Result<()> {
+        trace!("Handling request: {request:?}");
+        match request {
+            Request::Query(query) => match query {
+                Query::GetChunk(xor_name) => {
+                    let addr = ChunkAddress(xor_name);
+                    let chunk = self.storage.query(&addr).await?;
```
Comment (maqi) [inline safenode/src/node/mod.rs:102]: the self storage shall be just a read file from local disk.
so a `get` call instead of `query` shall be more precise ?

Also, I am wondering for the self storage, a direct read/write file shall be enough, no need to be `async` ?

Comment (maqi) [reply safenode/src/node/mod.rs:102]: also, the result of the data fetch may be an error.
in that case, the error shall be sent back as a response.
shall not just `unwrap` directly, which will result in a `terminated flow` and cause the request sender have to `time out`

File: safenode/src/node/mod.rs [hunk 8]
```diff
@@ -0,0 +1,132 @@
...
+                        Response::Query(QueryResponse::Chunk(chunk)),
+                        response_channel,
+                    )
+                    .await;
+                }
+                Query::GetDbc(_) => todo!(),
+            },
+            Request::Cmd(cmd) => match cmd {
+                Cmd::StoreChunk(chunk) => {
+                    self.storage.store(&chunk).await?;
```
Comment (maqi) [inline safenode/src/node/mod.rs:115]: same as query, the result of store shall be reported back.

File: safenode/src/network/msg/mod.rs (hunk 1 above)
Comment (RolandSherwin) [reply safenode/src/network/msg/mod.rs:10]: Do you think, `Action / ActionResult` and `Query / QueryResult` be a more apt name? The client should be at a higher level, so should we distinguish between them at this layer?

Comment (maqi) [reply safenode/src/network/msg/mod.rs:10]: I think currently we can just stay with `Request/Response` or `Action/AcitonResult`, to distinguish the message direcion, shall be enough.

File: safenode/src/node/api.rs (hunk 5 above)
Comment (RolandSherwin) [reply safenode/src/node/api.rs:73]: Aye, we got `#[debug(skip)]` over the bytes.

File: safenode/src/node/mod.rs (hunk 6 above)
Comment (maqi) [reply safenode/src/node/mod.rs:60]: right. but be careful that `recv` call is a blocking call.
which means may result in a `dead lock`

File: safenode/src/network/error.rs [hunk 9]
```diff
@@ -36,9 +36,12 @@ pub enum Error {
     #[error("Kademlia Store error: {0}")]
     KademliaStoreError(#[from] kad::store::Error),
 
-    #[error("The mpsc::receiever has been dropped")]
-    ReceieverDropped(#[from] mpsc::SendError),
+    #[error("The mpsc::receiever for `NetworkEvent` has been dropped")]
+    NetworkEventReceieverDropped(#[from] mpsc::error::SendError<NetworkEvent>),
```
Comment (jacderida) [inline safenode/src/network/error.rs:40]: There's a little typo here for both of these. `NetworkEventReceieverDropped` -> `NetworkEventReceiverDropped`.

File: safenode/src/network/event.rs [hunk 10]
```diff
@@ -89,40 +86,24 @@ impl NetworkSwarmLoop {
...
                 }
-                _ => {}
+                KademliaEvent::RoutingUpdated { .. } => {
+                    self.event_sender.send(NetworkEvent::PeerAdded).await?;
+                }
+                KademliaEvent::InboundRequest { request } => {
+                    info!("got inboumd request: {request:?}");
+                }
+                todo => {
+                    panic!("KademliaEvent has not been implemented: {todo:?}");
```
Comment (bochaco) [inline safenode/src/network/event.rs:105]: I wouldn't panic but log a warning, I think we may get an event and we don't want our node to crash just because we are not interested in such an event or because we still didn't handle it.

File: safenode/src/network/event.rs [hunk 11]
```diff
@@ -168,7 +148,7 @@ impl NetworkSwarmLoop {
             }
             SwarmEvent::IncomingConnectionError { .. } => {}
             SwarmEvent::Dialing(peer_id) => info!("Dialing {peer_id}"),
-            e => panic!("{e:?}"),
+            e => panic!("SwarmEvent has not been implemented: {e:?}"),
```
Comment (bochaco) [inline safenode/src/network/event.rs:151]: Sam as earlier, let's not panic but just log a msg

File: safenode/src/vault/api.rs [hunk 12]
```diff
@@ -0,0 +1,106 @@
...
+            ReplicatedData::Chunk(chunk) => Cmd::StoreChunk(chunk.clone()),
+            ReplicatedData::RegisterWrite(cmd) => Cmd::Register(cmd.clone()),
+            ReplicatedData::RegisterLog(_) => todo!(),
+        };
+        // forward to the other closest nodes if we're seeing the data for the first time
+        // return early if we already have the data with us
+        match self.storage.store(&cmd).await {
+            CmdResponse::StoreChunk(Err(_)) => return Ok(()),
+            CmdResponse::CreateRegister(Err(_)) => return Ok(()),
+            CmdResponse::EditRegister(Err(_)) => return Ok(()),
```
Comment (bochaco) [inline safenode/src/vault/api.rs:36]: I think you could match them all with `CmdResponse::StoreChunk(Err(_)) |CmdResponse::CreateRegister(Err(_)) | CmdResponse::EditRegister(Err(_)) => return Ok(())`
